replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.25.4-debian-12

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

containerPorts:
  http: 80

metrics:
  enabled: false
