replicaCount: 1

global:
  imageRegistry: registry-1.docker.io

image:
  registry: registry-1.docker.io
  repository: bitnamicharts/nginx

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

containerPorts:
  http: 80

metrics:
  enabled: false
