apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: infra-tools
spec:
  project: default

  ignoreDifferences:
    - group: batch
      kind: Job
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"
    - group: ""
      kind: ServiceAccount
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"
    - group: rbac.authorization.k8s.io
      kind: Role
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jqPathExpressions:
        - .metadata.annotations."helm.sh/hook"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 80.6.0
    helm:
      releaseName: monitoring
      skipCrds: false
      values: |
        alertmanager:
          enabled: false

        kubeApiServer:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false

        kubeStateMetrics:
          enabled: false

        grafana:
          enabled: true
          replicas: 1
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          sidecar:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi

        prometheusOperator:
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 400Mi

        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: true
            podMonitorSelectorNilUsesHelmValues: true
            ruleSelectorNilUsesHelmValues: true

            retention: 6h
            retentionSize: 1GB
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 1Gi

        prometheus-node-exporter:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
